### ISSUE TITLE
Bugs in FT3 version

### ISSUE THREAD

**Issue by Ne0-d3gen** [formtools/module-submission_history#4] opened 2017-12-24 23:00 UTC
Hey @benkeen, I'm loving the submissions history module. Few bugs though so far:

1) Again you have forgotten to update `include` to `ft_include` in all the .tpl files so module doesn't work - I think you need to tattoo this on your forehead for every future module update ;)

2) when you first run the module, and click on create submission history tables, you get the notification saying 'this may take some time' but then the process stops. It's only if you click on the button a second time after receiving this notification that the history tables are created and the notification updates.

3) issues with Form Backup module - when you create a copy of a form, using Form Backup after Submissions History is installed, it appears that a form history table is not being automatically created in your database. If you open Submissions History after backing up a form, you will see all sorts of errors in the submissions history table and you can't then open up the copied form because it throws an error regarding the missing history table that should be associated with that form.

Hope you have a great Christmas and manage to get some time away from Form Tools. Speak soon.

**Comment by benkeen** [comment] 2017-12-25 17:59
>  I think you need to tattoo this on your forehead for every future module update ;)

haha no kidding! That or actually getting some tests hooked up ;) 

Thanks for the bug reports, I'll fix them up today. Interesting about the Form Backup module problems... I hadn't considered that.

**Comment by benkeen** [comment] 2017-12-29 22:31
Hey @tomheaps, I just released new versions of this module and Form Backup. You should be able to just upgrade both and all will be fixed.

I couldn't reproduce your second issue though. Seemed to work fine in all cases.

**Comment by Ne0-d3gen** [comment] 2017-12-29 23:00
Thanks @benkeen, just upgraded and tested - all seems to be working to perfection now!
Have just posted an issue on the Submission ID Manager repository - no biggy but thought you would want to know.
Nearly there with the module updates now, keep your chin up.....

**Comment by tomheaps** [comment] 2018-01-01 21:35
Hey @benkeen, just noticed some further errors in some of my submission history tables - **this seems to occur only if a submission is created using the online Form Builder version of the form** - getting the following error messages in the changed by and changed fields columns:

> Notice: Undefined offset: 0 in /home/acutemed/warwickacutemedicine.co.uk/acportfolio/themes/default/cache/8cd9afd56e206bc7f9f33c4146217d879ef53afc_0.file.list_history.tpl.php on line 92
> 
> Notice: Undefined offset: 0 in /home/acutemed/warwickacutemedicine.co.uk/acportfolio/themes/default/cache/8cd9afd56e206bc7f9f33c4146217d879ef53afc_0.file.list_history.tpl.php on line 93

Please click on image below for screenshot:
  
![image](https://user-images.githubusercontent.com/13905479/34471216-5f6ce198-ef3b-11e7-992d-f36fe4f723bf.png)

**Comment by benkeen** [comment] 2018-01-06 05:13
haha thanks

**Closed as completed by benkeen** 2018-01-06 05:13 UTC
Labels: Bug
